#%RAML 1.0
title: S2VIZ
version: v1

types:
  channelMapTypes:
    enum: [visible,vegetation,waterVapor,infrared]

  generation_params:
    type: object
    properties:
      utmZone: integer
      latitudeBand: string
      gridSquare: string
      date: string
      channelMap: channelMapTypes

  combinedJpeg:
    type: file
    maxLength: 307200

  emptyResponse:
    type: object
    properties:
      msg: string
      descr: string
  errorResponse:
     type: object
     properties:
       msg: string
  infoResponse:
    type: object
    properties:
      info: string



/v1/s2viz:
  /help:
    post:
      responses:
        200:
          body:
            application/json:
              type: infoResponse
  /generate-image:
    description: create combined images of S2-Granule
    post:
      body:
        application/json:
          type: generation_params
      responses:
        201:
          body:
            image/jpeg:
              type: combinedJpeg
        400:
          body:
            application/json:
              type: emptyResponse
        404:
          body:
            application/json:
              type: emptyResponse
        500:
          body:
            application/json:
              type: errorResponse
